# Generated by Django 5.1.1 on 2024-10-16 05:53

import apps.essence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='hover_images',
            field=models.ImageField(default='hover_images.jpg', upload_to=apps.essence.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True),
        ),
    ]
