# Generated by Django 5.1.1 on 2024-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0002_remove_product_tag_product_hover_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('new', 'New'), ('old', 'Old')], default='new', max_length=10),
        ),
    ]
