# Generated by Django 5.1.1 on 2024-12-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='essence.coupon'),
        ),
    ]
