# Generated by Django 5.1.1 on 2024-12-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0004_cartorder_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='total',
        ),
    ]
