# Generated by Django 5.1.1 on 2024-10-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0004_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='essence.tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='title',
            field=models.CharField(default='tag', max_length=100),
        ),
    ]
