# Generated by Django 5.1.1 on 2024-11-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0008_product_life_product_mfd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='life',
            new_name='type',
        ),
    ]
