# Generated by Django 5.1.1 on 2024-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0009_rename_life_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='Oranic', max_length=100, null=True),
        ),
    ]
