export { default as Destinations } from './Destinations/Destinations'
export { default as DestinationFilter } from './Destinations/DestinationFilter'
export { default as Scholarship } from './Scholarship/Scholarship'
export { default as StudyDestination } from './StudyDestination/StudyDestination'
export { default as TopUniversity } from './TopUniversity/TopUniversity'
export { default as HeroVideo } from './Hero/HeroVideo'
export { default as Services } from './Services/Services'
